### ISSUE TITLE
make profile urls case-insensitive

### ISSUE THREAD

**Issue by lilyjordan** [manifoldmarkets/manifund#124]
unless usernames can collide if they're not case-sensitive (check)

at the very least, there's definitely some discrepancy where anything typed into the address bar becomes lowercase, but some usernames are case-sensitive, meaning you can only access certain profiles through search

**Comment by rachelweinberg12** [comment]
I think usernames can collide if they're not case sensitive, like the constraint on usernames in the database is just that the strings are unique, and 'A' is counted as a different character from 'a'.

Wdym "anything typed into the address bar becomes lowercase"?

**Comment by lilyjordan** [comment]
oh, turns out the address bar lowercasing might just be a [browser](https://stackoverflow.com/questions/50298340/chrome-changes-url-case) thing

it seems like this would still cause trouble, but exploring further it looks like Manifold does the same thing, so I guess it's fine after all
