### ISSUE TITLE
"Login" doesn't have an icon, 

### ISSUE THREAD

**Issue by saulmunn** [manifoldmarkets/manifund#130]
when you're logged out, all of the items on the sidebar (home, about, people, etc) have icons — except "login." feels weird & discontinuous

<img width="227" alt="Screenshot_2024-04-03_at_11 00 13_AM" src="https://github.com/manifoldmarkets/manifund/assets/100555686/e0859762-b060-4978-a023-01e0baff6b19">

**Comment by rachelweinberg12** [comment]
Fixed this!
