### ISSUE TITLE
Some Old Pages are Broken

### ISSUE THREAD

**Issue by casesandberg** [manifoldmarkets/manifund#68]
<img width="1455" alt="Screenshot 2023-11-14 at 7 59 23 PM" src="https://github.com/manifoldmarkets/manifund/assets/4633636/255c428c-19ec-4f3d-a1e3-12d9d19b1ab0">

Not sure if y'all are aware but there are some old pages that are broken. I was going through recent donations several seem to be broken: 
- https://manifund.org/projects/a-tool-for-making-well-sized-kelly-optimal-bets-on-manifold?tab=shareholders
- https://manifund.org/projects/telegram-bot-for-manifold-markets

**Comment by rachelweinberg12** [comment]
I'm not sure what was going on at the time but I think it was temporary and these pages work
